# Generated by Django 4.2.17 on 2025-06-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(help_text="The full 'From' header of the email")),
                ('html', models.TextField(help_text='HTML version of the email body')),
                ('subject', models.CharField(blank=True, help_text='Email subject line', max_length=255, null=True)),
                ('company', models.CharField(default='Miscellaneous', help_text="Derived company name from the sender's email domain", max_length=255)),
                ('raw_email', models.TextField(help_text='Complete raw MIME email content including all headers and parts')),
                ('headers', models.TextField(blank=True, help_text='Parsed email headers stored as text', null=True)),
                ('text_content', models.TextField(blank=True, help_text='Plain text version of the email body', null=True)),
                ('attachments', models.JSONField(default=dict, help_text='JSON object containing attachment metadata and base64 encoded content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the email record was created')),
                ('category', models.CharField(choices=[('marketing', 'Marketing / Promotions'), ('message', 'Primary / Messages')], db_index=True, default='message', help_text='Classification used for inbox organization (marketing vs primary messages)', max_length=10)),
                ('user', models.ForeignKey(help_text='The user who received this email', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='email_mgmt__created_180e9e_idx'), models.Index(fields=['company'], name='email_mgmt__company_e7102b_idx')],
            },
        ),
    ]
