# Generated by Django 4.2.17 on 2025-06-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='email',
            name='email_mgmt__created_180e9e_idx',
        ),
        migrations.RemoveIndex(
            model_name='email',
            name='email_mgmt__company_e7102b_idx',
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'company', '-created_at'], name='email_mgmt__user_id_032ec4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'category', '-created_at'], name='email_mgmt__user_id_d3b368_idx'),
        ),
    ]
