# Generated by Django 4.2.17 on 2025-06-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_type', models.TextField(blank=True)),
                ('receipt_currency_symbol', models.CharField(blank=True, max_length=5)),
                ('receipt_currency_code', models.CharField(blank=True, max_length=5)),
                ('item_count', models.PositiveIntegerField()),
                ('raw_email', models.TextField(blank=True, null=True)),
                ('raw_images', models.JSONField(blank=True, default=list, help_text='List of all uploaded image URLs for this receipt.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the receipt record was created.')),
                ('manual_entry', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='receipts', to='receipt_mgmt.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product_id', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, default=1, max_digits=10, null=True)),
                ('quantity_unit', models.TextField(blank=True, default='Units', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipt_mgmt.receipt')),
            ],
        ),
    ]
