# Generated by Django 4.2.17 on 2025-06-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_mgmt', '0002_add_trigram_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['receipt', 'id'], name='receipt_mgm_receipt_6ec2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', '-created_at'], name='receipt_mgm_user_id_09422a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'company', '-created_at'], name='receipt_mgm_user_id_4b2fae_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'receipt_type', '-created_at'], name='receipt_mgm_user_id_65a922_idx'),
        ),
    ]
