# Generated by Django 4.2.17 on 2025-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_mgmt', '0004_convert_receipt_type_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='company_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='country_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.TextField(blank=True, default='Unit(s)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='item_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
